'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'此源代码是由 Microsoft.VSDesigner 1.1.4322.2032 版自动生成。
'
Namespace SyncCacheService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SyncCacheServiceSoap", [Namespace]:="http://tempuri.org/Map/SyncCacheService")>  _
    Public Class SyncCacheService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Sub New()
            MyBase.New()
            Me.Url = "http://localhost:8001/WebService/SyncCacheService.asmx"
        End Sub

        '<remarks/>
        Public Sub New(ByVal url As String)
            MyBase.New()
            Me.Url = url
        End Sub

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Map/SyncCacheService/ClearAllSysTempFile", RequestNamespace:="http://tempuri.org/Map/SyncCacheService", ResponseNamespace:="http://tempuri.org/Map/SyncCacheService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ClearAllSysTempFile() As String
            Dim results() As Object = Me.Invoke("ClearAllSysTempFile", New Object(-1) {})
            Return CType(results(0), String)
        End Function

        '<remarks/>
        Public Function BeginClearAllSysTempFile(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ClearAllSysTempFile", New Object(-1) {}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndClearAllSysTempFile(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Map/SyncCacheService/ClearAllFuncTempFileByCode", RequestNamespace:="http://tempuri.org/Map/SyncCacheService", ResponseNamespace:="http://tempuri.org/Map/SyncCacheService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ClearAllFuncTempFileByCode(ByVal appCode As String) As String
            Dim results() As Object = Me.Invoke("ClearAllFuncTempFileByCode", New Object() {appCode})
            Return CType(results(0), String)
        End Function

        '<remarks/>
        Public Function BeginClearAllFuncTempFileByCode(ByVal appCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ClearAllFuncTempFileByCode", New Object() {appCode}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndClearAllFuncTempFileByCode(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Map/SyncCacheService/ClearAllFuncTempFile", RequestNamespace:="http://tempuri.org/Map/SyncCacheService", ResponseNamespace:="http://tempuri.org/Map/SyncCacheService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ClearAllFuncTempFile() As String
            Dim results() As Object = Me.Invoke("ClearAllFuncTempFile", New Object(-1) {})
            Return CType(results(0), String)
        End Function

        '<remarks/>
        Public Function BeginClearAllFuncTempFile(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ClearAllFuncTempFile", New Object(-1) {}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndClearAllFuncTempFile(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Map/SyncCacheService/ClearAllDeskTempFiles", RequestNamespace:="http://tempuri.org/Map/SyncCacheService", ResponseNamespace:="http://tempuri.org/Map/SyncCacheService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ClearAllDeskTempFiles() As Object
            Dim results() As Object = Me.Invoke("ClearAllDeskTempFiles", New Object(-1) {})
            Return CType(results(0), Object)
        End Function

        '<remarks/>
        Public Function BeginClearAllDeskTempFiles(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ClearAllDeskTempFiles", New Object(-1) {}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndClearAllDeskTempFiles(ByVal asyncResult As System.IAsyncResult) As Object
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), Object)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Map/SyncCacheService/ClearTempFiles", RequestNamespace:="http://tempuri.org/Map/SyncCacheService", ResponseNamespace:="http://tempuri.org/Map/SyncCacheService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ClearTempFiles(ByVal userGUID As String) As String
            Dim results() As Object = Me.Invoke("ClearTempFiles", New Object() {userGUID})
            Return CType(results(0), String)
        End Function

        '<remarks/>
        Public Function BeginClearTempFiles(ByVal userGUID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ClearTempFiles", New Object() {userGUID}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndClearTempFiles(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Map/SyncCacheService/ClearDeskTempFile", RequestNamespace:="http://tempuri.org/Map/SyncCacheService", ResponseNamespace:="http://tempuri.org/Map/SyncCacheService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ClearDeskTempFile(ByVal userGUID As String) As String
            Dim results() As Object = Me.Invoke("ClearDeskTempFile", New Object() {userGUID})
            Return CType(results(0), String)
        End Function

        '<remarks/>
        Public Function BeginClearDeskTempFile(ByVal userGUID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ClearDeskTempFile", New Object() {userGUID}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndClearDeskTempFile(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Map/SyncCacheService/ClearTempFilesByPattern", RequestNamespace:="http://tempuri.org/Map/SyncCacheService", ResponseNamespace:="http://tempuri.org/Map/SyncCacheService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ClearTempFilesByPattern(ByVal pattern As String) As Object
            Dim results() As Object = Me.Invoke("ClearTempFilesByPattern", New Object() {pattern})
            Return CType(results(0), Object)
        End Function

        '<remarks/>
        Public Function BeginClearTempFilesByPattern(ByVal pattern As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ClearTempFilesByPattern", New Object() {pattern}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndClearTempFilesByPattern(ByVal asyncResult As System.IAsyncResult) As Object
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), Object)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Map/SyncCacheService/Clear", RequestNamespace:="http://tempuri.org/Map/SyncCacheService", ResponseNamespace:="http://tempuri.org/Map/SyncCacheService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function Clear() As String
            Dim results() As Object = Me.Invoke("Clear", New Object(-1) {})
            Return CType(results(0), String)
        End Function

        '<remarks/>
        Public Function BeginClear(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Clear", New Object(-1) {}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndClear(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Map/SyncCacheService/Remove", RequestNamespace:="http://tempuri.org/Map/SyncCacheService", ResponseNamespace:="http://tempuri.org/Map/SyncCacheService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function Remove(ByVal key As String) As String
            Dim results() As Object = Me.Invoke("Remove", New Object() {key})
            Return CType(results(0), String)
        End Function

        '<remarks/>
        Public Function BeginRemove(ByVal key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Remove", New Object() {key}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndRemove(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Map/SyncCacheService/RemoveByPattern", RequestNamespace:="http://tempuri.org/Map/SyncCacheService", ResponseNamespace:="http://tempuri.org/Map/SyncCacheService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function RemoveByPattern(ByVal pattern As String) As String
            Dim results() As Object = Me.Invoke("RemoveByPattern", New Object() {pattern})
            Return CType(results(0), String)
        End Function

        '<remarks/>
        Public Function BeginRemoveByPattern(ByVal pattern As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RemoveByPattern", New Object() {pattern}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndRemoveByPattern(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Map/SyncCacheService/CheckConfig", RequestNamespace:="http://tempuri.org/Map/SyncCacheService", ResponseNamespace:="http://tempuri.org/Map/SyncCacheService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function CheckConfig(ByVal serverName As String) As String
            Dim results() As Object = Me.Invoke("CheckConfig", New Object() {serverName})
            Return CType(results(0), String)
        End Function

        '<remarks/>
        Public Function BeginCheckConfig(ByVal serverName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CheckConfig", New Object() {serverName}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndCheckConfig(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

    End Class
End Namespace
